spring.application.name=javadiamater-spring

logging.level.root=TRACE
logging.level.dk.i1.diameter.node=TRACE
logging.level.dk.i1.diameter.session=INFO
logging.level.dk.i1.diameter.session.AASession=INFO
logging.level.TestSession=INFO
